name: 'Java API/ABI compliance checker'
description: 'A action to check that Java API/ABI changes are backwards compatible'

inputs:
  key:
    description: 'The caching key'
    required: true
  file:
    description: 'The file path to the jar(s) to check'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'yellow'
